batch_size: 32
lr: 0.0001
weight_decay: 0.0001
num_epochs: 300
embed_dim: 768
device: "cuda"
clip_model_name: "openai/clip-vit-large-patch14"
max_length: 77
dataset_name: "t2m"
input_dim: 263
max_seq_length: 196
feat_bias: 5
pretrain_epochs: 5
lr_finetune: 0.00001
